import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
	new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
	environment {
		appName = "variable"
	}

	stages {
		stage("Paso 1") {
			agent {	label 'Falcon' }
			steps {
				script {
					sh "echo 'Hola Mundo 1!'"
				}
			}
		}
		stage("Paso 2") {
			agent {	label 'Falcon' }
			steps {
				script {
					sh "echo 'Hola Mundo 2!'"
				}
			}
		}
		stage("Paso 3") {
			agent {	label 'Container' }
			steps {
				script {
					sh "echo 'Hola Mundo 3!'"
				}
			}
		}
	}
	post {
		always {
			deleteDir()
			sh "echo 'Fase always'"
		}
		success {
			sh "echo 'Fase Success'"
		}
		failure {
			sh "echo 'Fase Failure'"
		}
	}
}