import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
	new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
	agent none
	environment {
		appName = "variable"
	}

	stages {
		stage("Paso 1 on Agent Falcon") {
			agent { label 'Falcon' }
			steps {
				script {
					sh "echo 'Hola Mundo 1!'"
				}
			}
		}
		stage("Paso 2 on Agent Falcon") {
			agent { label 'Falcon' }
			steps {
				script {
					sh "echo 'Hola Mundo 2!'"
				}
			}
		}
		stage("Paso 3 on Agent Container") {
			agent { label 'Container' }
			steps {
				script {
					sh "echo 'Hola Mundo 3!'"
				}
			}
		}
	}
	post {
		always {
			node ('Falcon') {
				deleteDir()
				sh "echo 'Fase always'"
			}
			node ('Container') {
				deleteDir()
				sh "echo 'Fase always'"
			}
		}
		success {
			node ('Falcon') {
				sh "echo 'Fase Success'"
			}
			node ('Container') {
				sh "echo 'Fase Success'"
			}
		}
		failure {
			node ('Falcon') {
				sh "echo 'Fase Failure'"
			}
			node ('Container') {
				sh "echo 'Fase Failure'"
			}
		}
	}
}